name: Amazon CodeGuru Security scan
on:
  workflow_dispatch:
    inputs:
      roleName:
        description: Role to assume
        required: true
        default: CodeGuruSecurityGitHubAccessRole
        type: string

permissions:
  id-token: write
  # for writing security events.
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::461731163182:role/${{ inputs.roleName }}
          aws-region: us-west-2
          role-session-name: GitHubActionScript

      - name: ECR Login
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: '324798398040'
          aws-region: us-west-2

      - name: Docker Pull
        run: |
          docker pull 324798398040.dkr.ecr.us-west-2.amazonaws.com/codegurusecurity-actions
          docker image tag 324798398040.dkr.ecr.us-west-2.amazonaws.com/codegurusecurity-actions codeguru:latest

      - uses: tlaiamz/cgs-action@v1
        with:
          source_path: .
          aws_region: us-west-2

      - name: print findings.
        run: |
          ls -l
          cat codeguru-security-results.sarif.json
